# Generated by Django 4.1.7 on 2023-11-19 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='Filename')),
                ('specialname', models.CharField(max_length=256, verbose_name='Special Name')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128, verbose_name='Folder Name')),
                ('parentdir', models.CharField(max_length=128, verbose_name='Parent')),
                ('public', models.BooleanField(verbose_name='Public')),
                ('files', models.ManyToManyField(related_name='files', to='core.files')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
        ),
    ]
