# Generated by Django 4.1.7 on 2023-11-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='name',
        ),
    ]
