# Generated by Django 4.1.7 on 2023-11-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_files_specialname_folders_specialname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folders',
            name='parentdir',
        ),
        migrations.AddField(
            model_name='folders',
            name='url',
            field=models.CharField(default=' ', max_length=128, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='folders',
            name='specialname',
            field=models.CharField(max_length=20, unique=True, verbose_name='Special Name'),
        ),
    ]
