# Generated by Django 4.1.7 on 2023-11-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_folders_parentdir_folders_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='access',
            field=models.ManyToManyField(blank=True, related_name='access', to='core.users'),
        ),
        migrations.AlterField(
            model_name='folders',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='files', to='core.files'),
        ),
    ]
