# Generated by Django 4.1.7 on 2023-11-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_folders_access_alter_folders_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='date',
            field=models.DateField(null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='folders',
            name='specialname',
            field=models.CharField(max_length=30, unique=True, verbose_name='Special Name'),
        ),
    ]
