# Generated by Django 4.1.7 on 2023-11-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_files_date_alter_folders_specialname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
