# Generated by Django 4.1.7 on 2023-11-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_files_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='time',
            field=models.TimeField(null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
