# Generated by Django 4.1.7 on 2023-11-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_files_time_alter_files_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='files',
            name='time',
            field=models.TimeField(verbose_name='Time'),
        ),
    ]
