# Generated by Django 4.1.7 on 2023-11-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_files_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='uploaded_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.users'),
            preserve_default=False,
        ),
    ]
