# Generated by Django 4.1.7 on 2023-11-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_files_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='date',
            field=models.DateField(default=0, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folders',
            name='time',
            field=models.TimeField(default=0, verbose_name='Time'),
            preserve_default=False,
        ),
    ]
