# Generated by Django 4.1.7 on 2023-11-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_folders_date_folders_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folders',
            name='date',
        ),
        migrations.RemoveField(
            model_name='folders',
            name='time',
        ),
    ]
