# Generated by Django 4.1.7 on 2023-11-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_folders_fdate_folders_ftime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folders',
            name='ftime',
        ),
    ]
