# Generated by Django 4.1.7 on 2023-11-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_folders_ftime'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='ftime',
            field=models.TimeField(default='17:30:20', verbose_name='Time'),
        ),
    ]
