# Generated by Django 4.1.7 on 2023-11-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_folders_ftime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='fdate',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='folders',
            name='ftime',
            field=models.TimeField(default='17:30:55', null=True, verbose_name='Time'),
        ),
    ]
